<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class InsertUsersSeeder extends Seeder
{

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Edson A. do Nascimento',
                'email' => 'pele@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'general_director',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vagner Mancini',
                'email' => 'vagner.mancini@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'director',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Abel Ferreira',
                'email' => 'abel.ferreira@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'director',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rogerio Ceni',
                'email' => 'rogerio.ceni@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'director',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ronaldinho Gaucho',
                'email' => 'ronaldinho.gaucho@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Roberto Firmino',
                'email' => 'roberto.firmino@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alex de Souza',
                'email' => 'alex.de.souza@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Françoaldo Souza',
                'email' => 'françoaldo.souza@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Romário Faria',
                'email' => 'romário.faria@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ricardo Goulart',
                'email' => 'ricardo.goulart@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dejan Petkovic',
                'email' => 'dejan.petkovic@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Deyverson Acosta',
                'email' => 'deyverson.acosta@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Harlei Silva',
                'email' => 'harlei.silva@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Walter Henrique',
                'email' => 'walter.henrique@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Afonso Afancar',
                'email' => 'afonso.afancar@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alceu Andreoli',
                'email' => 'alceu.andreoli@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Amalia Zago',
                'email' => 'amalia.zago@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Carlos Eduardo',
                'email' => 'carlos.eduardo@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luiz Felipe',
                'email' => 'luiz.felipe@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Breno',
                'email' => 'breno@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Emanuel',
                'email' => 'emanuel@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ryan',
                'email' => 'ryan@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vitor Hugo',
                'email' => 'vitor.hugo@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yuri',
                'email' => 'yuri@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Benjamin',
                'email' => 'benjamin@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Erick',
                'email' => 'erick@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Enzo Gabriel',
                'email' => 'enzo.gabriel@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fernando',
                'email' => 'fernando@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Joaquim',
                'email' => 'joaquim@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'André',
                'email' => 'andré@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Raul',
                'email' => 'raul@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marcelo',
                'email' => 'marcelo@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Julio César',
                'email' => 'julio.césar@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cauê',
                'email' => 'cauê@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Benício',
                'email' => 'benício@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vitor Gabriel',
                'email' => 'vitor.gabriel@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Augusto',
                'email' => 'augusto@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pedro Lucas',
                'email' => 'pedro.lucas@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luiz Gustavo',
                'email' => 'luiz.gustavo@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Giovanni',
                'email' => 'giovanni@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Renato',
                'email' => 'renato@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Diego',
                'email' => 'diego@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'João Paulo',
                'email' => 'joão.paulo@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Renan',
                'email' => 'renan@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luiz Fernando',
                'email' => 'luiz.fernando@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anthony',
                'email' => 'anthony@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lucas Gabriel',
                'email' => 'lucas.gabriel@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thales',
                'email' => 'thales@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luiz Miguel',
                'email' => 'luiz.miguel@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Henry',
                'email' => 'henry@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marcos Vinicius',
                'email' => 'marcos.vinicius@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kevin',
                'email' => 'kevin@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Levi',
                'email' => 'levi@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Enrico',
                'email' => 'enrico@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'João Lucas',
                'email' => 'joão.lucas@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hugo',
                'email' => 'hugo@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Luiz Guilherme',
                'email' => 'luiz.guilherme@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Matheus Henrique',
                'email' => 'matheus.henrique@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Miguel',
                'email' => 'miguel@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Davi',
                'email' => 'davi@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gabriel',
                'email' => 'gabriel@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arthur',
                'email' => 'arthur@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lucas',
                'email' => 'lucas@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Matheus',
                'email' => 'matheus@magazineaziul.com.br',
                'email_verified_at' => now(),
                'password' => Hash::make('123mudar'),
                'remember_token' => '',
                'role' => 'seller',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
